theme = "curzon"

[keys.insert]
pageup = "half_page_up"
pagedown = "half_page_down"

[keys.normal]
pageup = "half_page_up"
pagedown = "half_page_down"

[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
